/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comment_token1 = 1,
  aux_sym_comment_token2 = 2,
  sym_basic_name = 3,
  sym_unrestricted_name = 4,
  anon_sym_LT = 5,
  anon_sym_GT = 6,
  anon_sym_COLON_COLON = 7,
  anon_sym_COMMA = 8,
  sym_classifier_keyword = 9,
  sym_feature_keyword = 10,
  sym_dependency_keyword = 11,
  sym_from_keyword = 12,
  sym_to_keyword = 13,
  anon_sym_SEMI = 14,
  sym_source_file = 15,
  sym_comment = 16,
  sym_short_name = 17,
  sym_name = 18,
  sym_qualified_name = 19,
  sym_qualified_name_sequence = 20,
  sym_name_and_or_short_name = 21,
  sym_statement = 22,
  sym_classifier_statement = 23,
  sym_feature_statement = 24,
  sym_dependency_statement = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_qualified_name_repeat1 = 27,
  aux_sym_qualified_name_sequence_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_basic_name] = "basic_name",
  [sym_unrestricted_name] = "unrestricted_name",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_COMMA] = ", ",
  [sym_classifier_keyword] = "classifier_keyword",
  [sym_feature_keyword] = "feature_keyword",
  [sym_dependency_keyword] = "dependency_keyword",
  [sym_from_keyword] = "from_keyword",
  [sym_to_keyword] = "to_keyword",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_short_name] = "short_name",
  [sym_name] = "name",
  [sym_qualified_name] = "qualified_name",
  [sym_qualified_name_sequence] = "qualified_name_sequence",
  [sym_name_and_or_short_name] = "name_and_or_short_name",
  [sym_statement] = "statement",
  [sym_classifier_statement] = "classifier_statement",
  [sym_feature_statement] = "feature_statement",
  [sym_dependency_statement] = "dependency_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_qualified_name_repeat1] = "qualified_name_repeat1",
  [aux_sym_qualified_name_sequence_repeat1] = "qualified_name_sequence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_basic_name] = sym_basic_name,
  [sym_unrestricted_name] = sym_unrestricted_name,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_classifier_keyword] = sym_classifier_keyword,
  [sym_feature_keyword] = sym_feature_keyword,
  [sym_dependency_keyword] = sym_dependency_keyword,
  [sym_from_keyword] = sym_from_keyword,
  [sym_to_keyword] = sym_to_keyword,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_short_name] = sym_short_name,
  [sym_name] = sym_name,
  [sym_qualified_name] = sym_qualified_name,
  [sym_qualified_name_sequence] = sym_qualified_name_sequence,
  [sym_name_and_or_short_name] = sym_name_and_or_short_name,
  [sym_statement] = sym_statement,
  [sym_classifier_statement] = sym_classifier_statement,
  [sym_feature_statement] = sym_feature_statement,
  [sym_dependency_statement] = sym_dependency_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_qualified_name_repeat1] = aux_sym_qualified_name_repeat1,
  [aux_sym_qualified_name_sequence_repeat1] = aux_sym_qualified_name_sequence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_basic_name] = {
    .visible = true,
    .named = true,
  },
  [sym_unrestricted_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_classifier_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_feature_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_from_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_to_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_short_name] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_name_and_or_short_name] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_classifier_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_feature_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_name_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 18,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 34,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '\'', 4,
        ',', 1,
        '/', 5,
        ':', 8,
        ';', 55,
        '<', 45,
        '>', 46,
        'c', 22,
        'd', 13,
        'f', 16,
        't', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ';') ADVANCE(55);
      if (lookahead == '<') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == 'f') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(52);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 35:
      if (lookahead == 'y') ADVANCE(51);
      END_STATE();
    case 36:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_basic_name);
      if (lookahead == 'm') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_basic_name);
      if (lookahead == 'o') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_basic_name);
      if (lookahead == 'r') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_basic_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unrestricted_name);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_classifier_keyword);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_feature_keyword);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_dependency_keyword);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_from_keyword);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_from_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_to_keyword);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(5),
    [sym_unrestricted_name] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_classifier_keyword] = ACTIONS(1),
    [sym_feature_keyword] = ACTIONS(1),
    [sym_dependency_keyword] = ACTIONS(1),
    [sym_from_keyword] = ACTIONS(1),
    [sym_to_keyword] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_comment] = STATE(1),
    [sym_statement] = STATE(24),
    [sym_classifier_statement] = STATE(43),
    [sym_feature_statement] = STATE(43),
    [sym_dependency_statement] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [aux_sym_comment_token2] = ACTIONS(5),
    [sym_classifier_keyword] = ACTIONS(5),
    [sym_feature_keyword] = ACTIONS(9),
    [sym_dependency_keyword] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(13), 1,
      sym_basic_name,
    ACTIONS(15), 1,
      sym_unrestricted_name,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      sym_from_keyword,
    STATE(2), 1,
      sym_comment,
    STATE(8), 1,
      sym_name,
    STATE(17), 1,
      sym_qualified_name,
    STATE(23), 1,
      sym_short_name,
    STATE(35), 1,
      sym_qualified_name_sequence,
    STATE(36), 1,
      sym_name_and_or_short_name,
  [37] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      sym_feature_keyword,
    ACTIONS(11), 1,
      sym_dependency_keyword,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(24), 1,
      sym_statement,
    ACTIONS(5), 2,
      aux_sym_comment_token2,
      sym_classifier_keyword,
    STATE(43), 3,
      sym_classifier_statement,
      sym_feature_statement,
      sym_dependency_statement,
  [68] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_classifier_keyword,
    ACTIONS(28), 1,
      sym_feature_keyword,
    ACTIONS(31), 1,
      sym_dependency_keyword,
    STATE(24), 1,
      sym_statement,
    STATE(4), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(43), 3,
      sym_classifier_statement,
      sym_feature_statement,
      sym_dependency_statement,
  [99] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      anon_sym_SEMI,
    STATE(5), 1,
      sym_comment,
    STATE(18), 1,
      sym_short_name,
    STATE(37), 1,
      sym_name,
    STATE(44), 1,
      sym_name_and_or_short_name,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [128] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    STATE(6), 1,
      sym_comment,
    STATE(18), 1,
      sym_short_name,
    STATE(37), 1,
      sym_name,
    STATE(45), 1,
      sym_name_and_or_short_name,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [157] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(7), 1,
      sym_comment,
    STATE(11), 1,
      sym_name,
    STATE(17), 1,
      sym_qualified_name,
    STATE(33), 1,
      sym_qualified_name_sequence,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [180] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(40), 1,
      anon_sym_COLON_COLON,
    ACTIONS(44), 1,
      sym_from_keyword,
    STATE(8), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(42), 2,
      anon_sym_COMMA,
      sym_to_keyword,
  [203] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(9), 1,
      sym_comment,
    ACTIONS(46), 5,
      anon_sym_COLON_COLON,
      anon_sym_COMMA,
      sym_from_keyword,
      sym_to_keyword,
      anon_sym_SEMI,
  [220] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(10), 1,
      sym_comment,
    STATE(11), 1,
      sym_name,
    STATE(17), 1,
      sym_qualified_name,
    STATE(46), 1,
      sym_qualified_name_sequence,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [243] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(40), 1,
      anon_sym_COLON_COLON,
    STATE(11), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(42), 3,
      anon_sym_COMMA,
      sym_to_keyword,
      anon_sym_SEMI,
  [264] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(40), 1,
      anon_sym_COLON_COLON,
    STATE(12), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(48), 3,
      anon_sym_COMMA,
      sym_to_keyword,
      anon_sym_SEMI,
  [285] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(11), 1,
      sym_name,
    STATE(13), 1,
      sym_comment,
    STATE(17), 1,
      sym_qualified_name,
    STATE(41), 1,
      sym_qualified_name_sequence,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [308] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(11), 1,
      sym_name,
    STATE(14), 1,
      sym_comment,
    STATE(17), 1,
      sym_qualified_name,
    STATE(39), 1,
      sym_qualified_name_sequence,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [331] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(50), 1,
      anon_sym_COLON_COLON,
    STATE(15), 2,
      sym_comment,
      aux_sym_qualified_name_repeat1,
    ACTIONS(53), 3,
      anon_sym_COMMA,
      sym_to_keyword,
      anon_sym_SEMI,
  [350] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(11), 1,
      sym_name,
    STATE(16), 1,
      sym_comment,
    STATE(17), 1,
      sym_qualified_name,
    STATE(40), 1,
      sym_qualified_name_sequence,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [373] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      sym_comment,
    STATE(20), 1,
      aux_sym_qualified_name_sequence_repeat1,
    ACTIONS(57), 2,
      sym_to_keyword,
      anon_sym_SEMI,
  [393] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      sym_comment,
    STATE(32), 1,
      sym_name,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [413] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(19), 1,
      sym_comment,
    ACTIONS(59), 4,
      ts_builtin_sym_end,
      sym_classifier_keyword,
      sym_feature_keyword,
      sym_dependency_keyword,
  [429] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    STATE(20), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_qualified_name_sequence_repeat1,
    ACTIONS(61), 2,
      sym_to_keyword,
      anon_sym_SEMI,
  [449] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(11), 1,
      sym_name,
    STATE(21), 1,
      sym_comment,
    STATE(27), 1,
      sym_qualified_name,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [469] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(22), 1,
      sym_comment,
    ACTIONS(53), 4,
      anon_sym_COLON_COLON,
      anon_sym_COMMA,
      sym_to_keyword,
      anon_sym_SEMI,
  [485] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(13), 1,
      sym_basic_name,
    ACTIONS(15), 1,
      sym_unrestricted_name,
    ACTIONS(63), 1,
      sym_from_keyword,
    STATE(23), 1,
      sym_comment,
    STATE(32), 1,
      sym_name,
  [507] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(24), 1,
      sym_comment,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      sym_classifier_keyword,
      sym_feature_keyword,
      sym_dependency_keyword,
  [523] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    ACTIONS(70), 2,
      sym_to_keyword,
      anon_sym_SEMI,
    STATE(25), 2,
      sym_comment,
      aux_sym_qualified_name_sequence_repeat1,
  [541] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(22), 1,
      sym_name,
    STATE(26), 1,
      sym_comment,
    ACTIONS(15), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [558] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(27), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_COMMA,
      sym_to_keyword,
      anon_sym_SEMI,
  [573] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(28), 1,
      sym_comment,
    ACTIONS(72), 3,
      sym_basic_name,
      sym_unrestricted_name,
      anon_sym_SEMI,
  [588] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(72), 1,
      sym_unrestricted_name,
    STATE(29), 1,
      sym_comment,
    ACTIONS(74), 2,
      sym_basic_name,
      sym_from_keyword,
  [605] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(30), 1,
      sym_comment,
    ACTIONS(76), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [619] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(31), 1,
      sym_comment,
    ACTIONS(78), 2,
      sym_basic_name,
      sym_unrestricted_name,
  [633] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    STATE(32), 1,
      sym_comment,
    ACTIONS(80), 2,
      sym_from_keyword,
      anon_sym_SEMI,
  [647] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(82), 1,
      anon_sym_SEMI,
    STATE(33), 1,
      sym_comment,
  [660] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(84), 1,
      anon_sym_GT,
    STATE(34), 1,
      sym_comment,
  [673] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(86), 1,
      sym_to_keyword,
    STATE(35), 1,
      sym_comment,
  [686] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(88), 1,
      sym_from_keyword,
    STATE(36), 1,
      sym_comment,
  [699] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      sym_comment,
  [712] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    STATE(38), 1,
      sym_comment,
  [725] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym_comment,
  [738] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(94), 1,
      sym_to_keyword,
    STATE(40), 1,
      sym_comment,
  [751] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(96), 1,
      anon_sym_SEMI,
    STATE(41), 1,
      sym_comment,
  [764] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(98), 1,
      anon_sym_GT,
    STATE(42), 1,
      sym_comment,
  [777] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(100), 1,
      anon_sym_SEMI,
    STATE(43), 1,
      sym_comment,
  [790] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(102), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_comment,
  [803] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(104), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_comment,
  [816] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      aux_sym_comment_token2,
    ACTIONS(106), 1,
      sym_to_keyword,
    STATE(46), 1,
      sym_comment,
  [829] = 1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 157,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 203,
  [SMALL_STATE(10)] = 220,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 264,
  [SMALL_STATE(13)] = 285,
  [SMALL_STATE(14)] = 308,
  [SMALL_STATE(15)] = 331,
  [SMALL_STATE(16)] = 350,
  [SMALL_STATE(17)] = 373,
  [SMALL_STATE(18)] = 393,
  [SMALL_STATE(19)] = 413,
  [SMALL_STATE(20)] = 429,
  [SMALL_STATE(21)] = 449,
  [SMALL_STATE(22)] = 469,
  [SMALL_STATE(23)] = 485,
  [SMALL_STATE(24)] = 507,
  [SMALL_STATE(25)] = 523,
  [SMALL_STATE(26)] = 541,
  [SMALL_STATE(27)] = 558,
  [SMALL_STATE(28)] = 573,
  [SMALL_STATE(29)] = 588,
  [SMALL_STATE(30)] = 605,
  [SMALL_STATE(31)] = 619,
  [SMALL_STATE(32)] = 633,
  [SMALL_STATE(33)] = 647,
  [SMALL_STATE(34)] = 660,
  [SMALL_STATE(35)] = 673,
  [SMALL_STATE(36)] = 686,
  [SMALL_STATE(37)] = 699,
  [SMALL_STATE(38)] = 712,
  [SMALL_STATE(39)] = 725,
  [SMALL_STATE(40)] = 738,
  [SMALL_STATE(41)] = 751,
  [SMALL_STATE(42)] = 764,
  [SMALL_STATE(43)] = 777,
  [SMALL_STATE(44)] = 790,
  [SMALL_STATE(45)] = 803,
  [SMALL_STATE(46)] = 816,
  [SMALL_STATE(47)] = 829,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classifier_statement, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_statement, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_and_or_short_name, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name_sequence, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name_sequence, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name_and_or_short_name, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_name_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_name_sequence_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_short_name, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_short_name, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_and_or_short_name, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_statement, 6, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [90] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_statement, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_statement, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_classifier_statement, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_statement, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tree_sitter_sysmlv2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tree_sitter_sysmlv2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
